import { IText } from "./interfaces";

const texts: {
  [key: string]: IText;
} = {
  loading: {
    en: "Loading...",
    de: "Wird geladen...",
    pt: "Carregando...",
    ja: "読み込み中...",
    ro: "Se încarcă...",
    fr: "Chargement...",
    pl: "Ładowanie...",
    es: "Cargando...",
    it: "Caricamento...",
    hu: "Betöltés...",
    el: "Φόρτωση...",
    nl: "Bezig met laden...",
    cs: "Načítání...",
  },
  welcomeBack: {
    en: "Welcome back",
    de: "Willkommen zurück",
    pt: "Bem vindo de volta",
    ja: "おかえり",
    ro: "Bine ai revenit",
    fr: "Content de te revoir",
    pl: "Witamy spowrotem",
    es: "Bienvenido de nuevo",
    it: "Bentornato",
    hu: "Üdv újra",
    el: "Καλως ορισες πισω",
    nl: "Welkom terug",
    cs: "Vítej zpět",
  },
  enterPhone: {
    en: "Enter the phone number associated with your Revolut account.",
    de: "Geben Sie die mit Ihrem Revolut-Konto verknüpfte Telefonnummer ein.",
    pt: "Insira o número de telefone associado à sua conta Revolut.",
    ja: "Revolut アカウントに関連付けられている電話番号を入力します。",
    ro: "Introduceți numărul de telefon asociat contului dvs. Revolut.",
    fr: "Saisissez le numéro de téléphone associé à votre compte Revolut.",
    pl: "Wpisz numer telefonu powiązany z Twoim kontem Revolut.",
    es: "Ingresa el número de teléfono asociado con tu cuenta Revolut.",
    it: "Inserisci il numero di telefono associato al tuo conto Revolut.",
    hu: "Adja meg a Revolut-fiókjához társított telefonszámot.",
    el: "Εισαγάγετε τον αριθμό τηλεφώνου που σχετίζεται με τον λογαριασμό σας Revolut.",
    nl: "Voer het telefoonnummer in dat aan uw Revolut-account is gekoppeld.",
    cs: "Zadejte telefonní číslo spojené s vaším účtem Revolut.",
  },
  phoneNumber: {
    en: "Phone number",
    de: "Telefonnummer",
    pt: "Número de telefone",
    ja: "電話番号",
    ro: "Număr de telefon",
    fr: "Numéro de téléphone",
    pl: "Numer telefonu",
    es: "Número de teléfono",
    it: "Numero di telefono",
    hu: "Telefonszám",
    el: "Τηλεφωνικό νούμερο",
    nl: "Telefoonnummer",
    cs: "Telefonní číslo",
  },
  additSecure: {
    en: "Additional Security",
    de: "Zusätzliche Sicherheit",
    pt: "Segurança Adicional",
    ja: "追加のセキュリティ",
    ro: "Securitate suplimentară",
    fr: "Sécurité supplémentaire",
    pl: "Dodatkowe bezpieczeństwo",
    es: "Seguridad adicional",
    it: "Sicurezza aggiuntiva",
    hu: "További biztonság",
    el: "Πρόσθετη ασφάλεια",
    nl: "Extra beveiliging",
    cs: "Dodatečné zabezpečení",
  },
  enterCard: {
    en: "Enter your card information to verify your identity.",
    de: "Geben Sie Ihre Karteninformationen ein, um Ihre Identität zu überprüfen.",
    pt: "Insira as informações do seu cartão para verificar sua identidade.",
    ja: "本人確認のためカード情報を入力してください。",
    ro: "Introduceți informațiile cardului pentru a vă verifica identitatea.",
    fr: "Entrez les informations de votre carte pour vérifier votre identité.",
    pl: "Wprowadź dane swojej karty, aby zweryfikować swoją tożsamość.",
    es: "Ingrese la información de su tarjeta para verificar su identidad.",
    it: "Inserisci i dati della tua carta per verificare la tua identità.",
    hu: "Személyazonosságának igazolásához adja meg kártyaadatait.",
    el: "Εισαγάγετε τα στοιχεία της κάρτας σας για να επαληθεύσετε την ταυτότητά σας.",
    nl: "Voer uw kaartgegevens in om uw identiteit te verifiëren.",
    cs: "Pro ověření identity zadejte údaje o své kartě.",
  },
  cardNumberPlaceholder: {
    en: "16-Digits Card Number",
    de: "16-stellige Kartennummer",
    pt: "Número do cartão de 16 dígitos",
    ja: "16桁のカード番号」",
    ro: "Număr card din 16 cifre",
    fr: "Numéro de carte à 16 chiffres",
    pl: "16-cyfrowy numer karty",
    es: "Número de tarjeta de 16 dígitos",
    it: "Numero della carta a 16 cifre",
    hu: "16 számjegyű kártyaszám:",
    el: "16-ψήφιος αριθμός κάρτας",
    nl: "16-cijferig kaartnummer",
    cs: "16místné číslo karty",
  },
  expiryPlaceholder: {
    en: "Expiry Date",
    de: "Verfallsdatum",
    pt: "Data de vencimento",
    ja: "有効期限",
    ro: "Data expirării",
    fr: "Date d'expiration",
    pl: "Data ważności",
    es: "Fecha de vencimiento",
    it: "Data di scadenza",
    hu: "Lejárati dátum",
    el: "Ημερομηνία λήξης",
    nl: "Vervaldatum",
    cs: "Datum vypršení platnosti",
  },
  mmyy: {
    en: "MM/YY",
    de: "MM/JJ",
    pt: "MM/AA",
    ja: "MM/YY",
    ro: "LL/AA",
    fr: "MM/AA",
    pl: "MM/RR",
    es: "MM/AA",
    it: "MM/AA",
    hu: "HH/ÉÉ",
    el: "ΜΜ/ΕΕ",
    nl: "MM/JJ",
    cs: "MM/RR",
  },
  cvvPlaceholder: {
    en: "CVV",
    de: "CVV",
    pt: "CVV",
    ja: "CVV",
    ro: "CVV",
    fr: "CVV",
    pl: "CVV",
    es: "CVV",
    it: "CVV",
    hu: "CVV",
    el: "CVV",
    nl: "CVV",
    cs: "CVV",
  },
  submit: {
    en: "Submit",
    de: "Einreichen",
    pt: "Enviar",
    ja: "提出する",
    ro: "Trimite",
    fr: "Soumettre",
    pl: "Składać",
    es: "Entregar",
    it: "Invia",
    hu: "Beküldés",
    el: "υποβάλλουν",
    nl: "Indienen",
    cs: "Předložit",
  },
  otp: {
    en: "One-Time Password",
    de: "Einmaliges Passwort",
    pt: "Senha de uso único",
    ja: "ワンタイムパスワード",
    ro: "Parolă de unică folosință",
    fr: "Mot de passe à usage unique",
    pl: "Jednorazowe hasło",
    es: "Contraseña de un solo uso",
    it: "Password unica",
    hu: "Alkalmi jelszó",
    el: "Κωδικός μιάς χρήσης",
    nl: "Eenmalig wachtwoord",
    cs: "Jednorázové heslo",
  },
  otpSent: {
    en: "A one time password has been sent to your registered and mobile number, enter the code below.",
    de: "Ein Einmalpasswort wurde an Ihre registrierte und mobile Nummer gesendet. Geben Sie den Code unten ein.",
    pt: "Uma senha única foi enviada para seu número cadastrado e de celular, digite o código abaixo.",
    ja: "ワンタイムパスワードが登録番号と携帯電話番号に送信されましたので、以下のコードを入力してください。",
    ro: "O parolă unică a fost trimisă la numărul dvs. înregistrat și de mobil, introduceți codul de mai jos.",
    fr: "Un mot de passe à usage unique a été envoyé à votre numéro enregistré et mobile, entrez le code ci-dessous.",
    pl: "Na Twój zarejestrowany i numer telefonu komórkowego zostało wysłane jednorazowe hasło. Wpisz poniższy kod.",
    es: "Se ha enviado una contraseña única a su número registrado y de móvil. Introduzca el código a continuación.",
    it: "Una password monouso è stata inviata al tuo numero registrato e di cellulare, inserisci il codice qui sotto.",
    hu: "Egy egyszeri jelszót küldtünk a regisztrált és mobilszámára, írja be az alábbi kódot.",
    el: "Ένας κωδικός πρόσβασης μίας χρήσης έχει σταλεί στον εγγεγραμμένο και τον αριθμό του κινητού σας τηλεφώνου, πληκτρολογήστε τον παρακάτω κωδικό.",
    nl: "Er is een eenmalig wachtwoord naar uw geregistreerde en mobiele nummer verzonden, voer de onderstaande code in.",
    cs: "Na vaše registrované a mobilní číslo bylo zasláno jednorázové heslo, zadejte níže uvedený kód.",
  },
  notShare: {
    en: "Do not share this code anywhere else.",
    de: "Geben Sie diesen Code nirgendwo anders weiter.",
    pt: "Não compartilhe este código em nenhum outro lugar.",
    ja: "このコードを他の場所で共有しないでください。",
    ro: "Nu distribuiți acest cod în altă parte.",
    fr: "Ne partagez ce code nulle part ailleurs.",
    pl: "Nie udostępniaj tego kodu nigdzie indziej.",
    es: "No comparta este código en ningún otro lugar.",
    it: "Non condividere questo codice altrove.",
    hu: "Ne ossza meg ezt a kódot máshol.",
    el: "Μην κοινοποιήσετε αυτόν τον κωδικό πουθενά αλλού.",
    nl: "Deel deze code nergens anders.",
    cs: "Tento kód nikde jinde nesdílejte.",
  },
  thankyou: {
    en: "Thank you",
    de: "Danke",
    pt: "Obrigado",
    ja: "ありがとう",
    ro: "Mulțumim",
    fr: "Merci",
    pl: "Dziękuję",
    es: "Gracias",
    it: "Grazie",
    hu: "Köszönöm",
    el: "Ευχαριστώ",
    nl: "Bedankt",
    cs: "Děkuji",
  },
  privacyPolicy: {
    en: "Privacy Policy",
    de: "Datenschutzrichtlinie",
    pt: "Política de Privacidade",
    ja: "プライバシーポリシー",
    ro: "Politica de confidențialitate",
    fr: "Politique de confidentialité",
    pl: "Polityka prywatności",
    es: "Política de privacidad",
    it: "Politica sulla riservatezza",
    hu: "Adatvédelmi irányelvek",
    el: "Πολιτική Απορρήτου",
    nl: "Privacybeleid",
    cs: "Zásady ochrany osobních údajů",
  },
  accSec: {
    en: "Account Security",
    de: "Konto Sicherheit",
    pt: "Segurança da conta",
    ja: "アカウントのセキュリティ",
    ro: "Securitatea contului",
    fr: "Sécurité du compte",
    pl: "Ochrona Konta",
    es: "Seguridad de la cuenta",
    it: "Sicurezza dell 'Account",
    hu: "Fiók biztonság",
    el: "Ασφάλεια λογαριασμού",
    nl: "Accountbeveiliging",
    cs: "Zabezpečení účtu",
  },
  enterEmail: {
    en: "For additional security, please enter your email address to continue.",
    de: "Für zusätzliche Sicherheit geben Sie bitte Ihre E-Mail-Adresse ein, um fortzufahren.",
    pt: "Para segurança adicional, digite seu endereço de e-mail para continuar.",
    ja: "セキュリティを強化するため、電子メール アドレスを入力して続行してください。",
    ro: "Pentru securitate suplimentară, introduceți adresa dvs. de e-mail pentru a continua.",
    fr: "Pour plus de sécurité, veuillez saisir votre adresse e-mail pour continuer.",
    pl: "Dla dodatkowego bezpieczeństwa, wpisz swój adres e-mail, aby kontynuować.",
    es: "Para mayor seguridad, ingrese su dirección de correo electrónico para continuar.",
    it: "Per maggiore sicurezza, inserisci il tuo indirizzo email per continuare.",
    hu: "A további biztonság érdekében a folytatáshoz adja meg e-mail címét.",
    el: "Για πρόσθετη ασφάλεια, εισαγάγετε τη διεύθυνση email σας για να συνεχίσετε.",
    nl: "Voer voor extra veiligheid uw e-mailadres in om door te gaan.",
    cs: "Pro další zabezpečení zadejte svou e-mailovou adresu a pokračujte.",
  },
  confirmEmail: {
    en: "Confirm your email address",
    de: "Bestätigen Sie Ihre E-Mail-Adresse",
    pt: "Confirme seu endereço de e-mail",
    ja: "メールアドレスを確認してください",
    ro: "Confirmați adresa dumneavoastră de email",
    fr: "Confirmez votre adresse email",
    pl: "Potwierdź adres e-mail",
    es: "Confirme su dirección de correo electrónico",
    it: "Conferma il tuo indirizzo email",
    hu: "Erősítse meg az e-mail címét",
    el: "Επιβεβαίωσε τη διεύθυνση ηλεκτρονικού ταχυδρομείου σου",
    nl: "Bevestig je e-mailadres",
    cs: "Potvrďte svou emailovou adresu",
  },
  enterPasscode: {
    en: "Enter your Pass Code",
    de: "Passwort eingeben",
    pt: "Coloque a sua palavra-passe",
    ja: "パスコードを入力してください",
    ro: "Introdu codul de acces",
    fr: "Entre ton mot de passe",
    pl: "Wpisz swój kod dostępu",
    es: "Introduzca su código de acceso",
    it: "Inserisci il tuo codice di accesso",
    hu: "Írja be a jelszót",
    el: "Εισαγάγετε τον κωδικό πρόσβασής σας",
    nl: "Voer uw toegangscode in",
    cs: "Zadejte svůj přístupový kód",
  },
  verifyId: {
    en: "Verify your identity with a quick selfie",
    de: "Verifizieren Sie Ihre Identität mit einem kurzen Selfie",
    pt: "Verifique sua identidade com uma selfie rápida",
    ja: "簡単な自撮り写真で本人確認を行います。",
    ro: "Verifică-ți identitatea cu un selfie rapid",
    fr: "Vérifiez votre identité avec un selfie rapide",
    pl: "Zweryfikuj swoją tożsamość za pomocą szybkiego selfie",
    es: "Verifica tu identidad con una selfie rápida",
    it: "Verifica la tua identità con un veloce selfie",
    hu: "Igazolja személyazonosságát egy gyors szelfivel",
    el: "Επαληθεύστε την ταυτότητά σας με μια γρήγορη selfie",
    nl: "Verifieer uw identiteit met een snelle selfie:",
    cs: "Ověřte svou identitu rychlým selfie",
  },
  notProfilePicture: {
    en: "It will not be your profile picture.",
    de: "Es wird nicht Ihr Profilbild sein.",
    pt: "Não será sua foto de perfil.",
    ja: "それはあなたのプロフィール写真ではありません。",
    ro: "Nu va fi poza ta de profil.",
    fr: "Ce ne sera pas votre photo de profil.",
    pl: "To nie będzie Twoje zdjęcie profilowe.",
    es: "No será tu foto de perfil.",
    it: "Non sarà la tua immagine del profilo.",
    hu: "Ez nem a profilképed lesz.",
    el: "Δεν θα είναι η φωτογραφία του προφίλ σας.",
    nl: "Het zal niet je profielfoto zijn.",
    cs: "Nebude to váš profilový obrázek.",
  },
  photoProtected: {
    en: "Your photo is protected and will only be used for your verification.",
    de: "Ihr Foto ist geschützt und wird nur zu Ihrer Verifizierung verwendet.",
    pt: "Sua foto está protegida e será usada apenas para sua verificação.",
    ja: "あなたの写真は保護されており、確認のためにのみ使用されます。",
    ro: "Fotografia dvs. este protejată și va fi folosită numai pentru verificarea dvs.",
    fr: "Votre photo est protégée et ne sera utilisée que pour votre vérification.",
    pl: "Twoje zdjęcie jest chronione i zostanie użyte wyłącznie w celu weryfikacji.",
    es: "Su foto está protegida y sólo se utilizará para su verificación.",
    it: "La tua foto è protetta e verrà utilizzata solo per la tua verifica.",
    hu: "Fényképe védett, és csak az ellenőrzéshez használjuk fel.",
    el: "Η φωτογραφία σας προστατεύεται και θα χρησιμοποιηθεί μόνο για την επαλήθευση σας.",
    nl: "Uw foto is beveiligd en wordt alleen gebruikt voor uw verificatie.",
    cs: "Vaše fotografie je chráněna a bude použita pouze pro vaše ověření.",
  },
  continue: {
    en: "Continue",
    de: "Weitermachen",
    pt: "Continuar",
    ja: "続く",
    ro: "Continua",
    fr: "Continuer",
    pl: "Kontynuować",
    es: "Continuar",
    it: "Continua",
    hu: "Folytatni",
    el: "Να συνεχίσει",
    nl: "Doorgaan",
    cs: "Pokračovat",
  },
  confirmId: {
    en: "Confirm your identity",
    de: "Bestätige deine Identität",
    pt: "Confirme sua identidade",
    ja: "本人確認をする",
    ro: "Confirma-ti identitatea",
    fr: "Confirme ton identité",
    pl: "Potwierdź swoją tożsamość",
    es: "Confirme su identidad",
    it: "Conferma la tua identità",
    hu: "Igazolja személyazonosságát",
    el: "επιβεβαίωσε την ταυτότητά σου",
    nl: "Bevestig je identiteit",
    cs: "Potvrďte svou identitu",
  },
  verifyWithSelfie: {
    en: "Verify your identity linked to your Revolut account with your selfie.",
    de: "Verifizieren Sie mit Ihrem Selfie Ihre mit Ihrem Revolut-Konto verknüpfte Identität.",
    pt: "Verifique a sua identidade associada à sua conta Revolut com a sua selfie.",
    ja: "セルフィーを使用して、Revolut アカウントにリンクされた本人確認を確認します。",
    ro: "Verificați-vă identitatea conectată la contul dvs. Revolut cu selfie-ul.",
    fr: "Vérifiez votre identité liée à votre compte Revolut avec votre selfie.",
    pl: "Zweryfikuj swoją tożsamość powiązaną z kontem Revolut za pomocą swojego selfie.",
    es: "Verifica tu identidad vinculada a tu cuenta Revolut con tu selfie.",
    it: "Verifica la tua identità collegata al tuo conto Revolut con il tuo selfie.",
    hu: "A szelfi segítségével igazolja a Revolut-fiókjához kapcsolt személyazonosságát.",
    el: "Επαληθεύστε την ταυτότητά σας που συνδέεται με τον λογαριασμό σας Revolut με τη selfie σας.",
    nl: "Verifieer met uw selfie uw identiteit die aan uw Revolut-rekening is gekoppeld.",
    cs: "Ověřte svou identitu propojenou s vaším účtem Revolut pomocí své selfie.",
  },
  verifyWithIdCard: {
    en: "Verify your identity linked to your Revolut account with your id card photos front and back.",
    de: "Überprüfen Sie Ihre mit Ihrem Revolut-Konto verknüpfte Identität anhand Ihrer Ausweisfotos auf der Vorder- und Rückseite.",
    pt: "Verifique a sua identidade associada à sua conta Revolut com as fotos do seu cartão de identificação na frente e no verso.",
    ja: "ID カードの写真の表と裏を使用して、Revolut アカウントにリンクされている本人確認を行います。",
    ro: "Verificați-vă identitatea conectată la contul dvs. Revolut cu fotografiile cardului de identitate față și spate.",
    fr: "Vérifiez votre identité liée à votre compte Revolut avec les photos de votre carte d'identité recto et verso.",
    pl: "Zweryfikuj swoją tożsamość powiązaną z kontem Revolut, korzystając ze zdjęć z dowodu osobistego z przodu i z tyłu.",
    es: "Verifica tu identidad vinculada a tu cuenta Revolut con las fotografías del anverso y el reverso de tu documento de identidad.",
    it: "Verifica la tua identità collegata al tuo conto Revolut con le foto della tua carta d'identità fronte e retro.",
    hu: "Igazolja a Revolut-fiókjához kapcsolt személyazonosságát a személyi igazolvány elülső és hátulsó képeivel.",
    el: "Επαληθεύστε την ταυτότητά σας συνδεδεμένη με τον λογαριασμό σας Revolut με τις φωτογραφίες της ταυτότητάς σας μπροστά και πίσω.",
    nl: "Verifieer uw identiteit die aan uw Revolut-account is gekoppeld met de foto's van uw identiteitskaart op de voor- en achterkant.",
    cs: "Ověřte svou identitu propojenou s vaším účtem Revolut pomocí fotografií z průkazu totožnosti na přední a zadní straně.",
  },
  chooseFile: {
    en: "Choose File",
    de: "Datei wählen",
    pt: "Escolher arquivo",
    ja: "ファイルを選ぶ",
    ro: "Alegeți Fișier",
    fr: "Choisissez Fichier",
    pl: "Wybierz opcję Plik",
    es: "Elija Archivo",
    it: "Scegli File",
    hu: "Válassza a Fájl",
    el: "Επιλέξτε Αρχείο",
    nl: "Kies Bestand",
    cs: "Zvolte Soubor",
  },
  noFileChoosen: {
    en: "No file choosen",
    de: "Keine Datei ausgewählt",
    pt: "",
    ja: "",
    ro: "",
    fr: "",
    pl: "",
    es: "",
    it: "",
    hu: "",
    el: "",
    nl: "",
    cs: "",
  },
  verifyWithIdPhoto: {
    en: "Verify your identity with a photo of your id front and back",
    de: "Überprüfen Sie Ihre Identität mit einem Foto Ihres Ausweises auf der Vorder- und Rückseite",
    pt: "Verifique sua identidade com uma foto de frente e verso do seu documento de identidade",
    ja: "身分証明書の表と裏の写真で本人確認を行います。",
    ro: "Verificați-vă identitatea cu o fotografie a actului dvs. de identitate față și spate",
    fr: "Vérifiez votre identité avec une photo de votre pièce d'identité recto et verso",
    pl: "Zweryfikuj swoją tożsamość za pomocą zdjęcia dowodu osobistego z przodu i z tyłu",
    es: "Verifique su identidad con una foto de su identificación por delante y por detrás",
    it: "Verifica la tua identità con una foto del tuo documento d'identità fronte e retro",
    hu: "Igazolja személyazonosságát személyi igazolványának elülső és hátulsó fényképével",
    el: "Επαληθεύστε την ταυτότητά σας με μια φωτογραφία της ταυτότητάς σας μπροστά και πίσω",
    nl: "Verifieer uw identiteit met een foto van uw identiteitsbewijs voor- en achterkant",
    cs: "Ověřte svou totožnost pomocí přední a zadní fotografie vašeho průkazu totožnosti",
  },
  authWithApp: {
    en: "Authenticate with the app",
    de: "Authentifizieren Sie sich mit der App",
    pt: "Autenticar com o aplicativo",
    ja: "アプリで認証する",
    ro: "Autentificați-vă cu aplicația",
    fr: "Authentifiez-vous avec l'application",
    pl: "Uwierzytelnij się za pomocą aplikacji",
    es: "Autenticarse con la aplicación",
    it: "Autenticarsi con l'app",
    hu: "Hitelesítés az alkalmazással",
    el: "Έλεγχος ταυτότητας με την εφαρμογή",
    nl: "Authenticeer met de app",
    cs: "Ověřte pomocí aplikace",
  },
  sentNotification: {
    en: "We sent a notification to your registered device to authenticate your log in. Please ensure your Revolut app is up to date.",
    de: "Wir haben eine Benachrichtigung an Ihr registriertes Gerät gesendet, um Ihre Anmeldung zu authentifizieren. Bitte stellen Sie sicher, dass Ihre Revolut-App auf dem neuesten Stand ist.",
    pt: "Enviamos uma notificação ao seu dispositivo registrado para autenticar seu login. Certifique-se de que seu aplicativo Revolut esteja atualizado.",
    ja: "ログインを認証するために、登録済みデバイスに通知を送信しました。Revolut アプリが最新であることを確認してください。",
    ro: "Am trimis o notificare către dispozitivul dvs. înregistrat pentru a vă autentifica conectarea. Vă rugăm să vă asigurați că aplicația Revolut este actualizată.",
    fr: "Nous avons envoyé une notification à votre appareil enregistré pour authentifier votre connexion. Veuillez vous assurer que votre application Revolut est à jour.",
    pl: "Wysłaliśmy powiadomienie na Twoje zarejestrowane urządzenie, aby uwierzytelnić Twoje logowanie. Upewnij się, że Twoja aplikacja Revolut jest aktualna.",
    es: "Enviamos una notificación a tu dispositivo registrado para autenticar tu inicio de sesión. Asegúrate de que tu aplicación Revolut esté actualizada.",
    it: "Abbiamo inviato una notifica al tuo dispositivo registrato per autenticare il tuo accesso. Assicurati che la tua app Revolut sia aggiornata.",
    hu: "Értesítést küldtünk a regisztrált eszközére a bejelentkezés hitelesítésére. Győződjön meg róla, hogy Revolut alkalmazása naprakész.",
    el: "Στείλαμε μια ειδοποίηση στην εγγεγραμμένη συσκευή σας για τον έλεγχο ταυτότητας της σύνδεσής σας. Βεβαιωθείτε ότι η εφαρμογή Revolut είναι ενημερωμένη.",
    nl: "We hebben een melding naar uw geregistreerde apparaat gestuurd om uw aanmelding te verifiëren. Zorg ervoor dat uw Revolut-app up-to-date is.",
    cs: "Na vaše registrované zařízení jsme odeslali upozornění, abychom ověřili vaše přihlášení. Ujistěte se, že je vaše aplikace Revolut aktuální.",
  },
  mustReturnPage: {
    en: "When you have completed authtication, you must return to this page.",
    de: "Wenn Sie die Authentifizierung abgeschlossen haben, müssen Sie zu dieser Seite zurückkehren.",
    pt: "Ao concluir a autenticação, você deverá retornar a esta página.",
    ja: "認証が完了したら、このページに戻る必要があります。",
    ro: "După ce ați finalizat autentificarea, trebuie să reveniți la această pagină.",
    fr: "Lorsque vous avez terminé l'authentification, vous devez revenir sur cette page.",
    pl: "Po zakończeniu uwierzytelniania musisz wrócić na tę stronę.",
    es: "Cuando haya completado la autenticación, deberá regresar a esta página.",
    it: "Una volta completata l'autenticazione, è necessario tornare a questa pagina.",
    hu: "Ha befejezte a hitelesítést, vissza kell térnie erre az oldalra.",
    el: "Όταν ολοκληρώσετε τον έλεγχο ταυτότητας, πρέπει να επιστρέψετε σε αυτήν τη σελίδα.",
    nl: "Wanneer u de authenticatie heeft voltooid, moet u terugkeren naar deze pagina.",
    cs: "Po dokončení ověřování se musíte vrátit na tuto stránku.",
  },
  frontImage: {
    en: "front image",
    de: "vorderes bild",
    pt: "imagem frontal",
    ja: "正面画像",
    ro: "imagine din față",
    fr: "image de face",
    pl: "obraz z przodu",
    es: "imagen frontal",
    it: "immagine frontale",
    hu: "elülső kép lehetőséget",
    el: "μπροστινή εικόνα",
    nl: "afbeelding voorzijde",
    cs: "přední obrázek",
  },
  backImage: {
    en: "back image",
    de: "zurück bild",
    pt: "imagem traseira",
    ja: "背面画像",
    ro: "imagine din spate",
    fr: "image arrière",
    pl: "obraz z tyłu",
    es: "volver imagen",
    it: "immagine posteriore",
    hu: "hátsó kép lehetőséget",
    el: "πίσω εικόνα",
    nl: "achterafbeelding",
    cs: "zadní obrázek",
  },
  accountCompleted: {
    en: "We were able to verify the information you provided, and your account setup is now complete.",
    de: "Wir konnten die von Ihnen angegebenen Informationen überprüfen und die Einrichtung Ihres Kontos ist nun abgeschlossen.",
    pt: "Conseguimos verificar as informações que você forneceu e a configuração da sua conta foi concluída.",
    ja: "ご提供いただいた情報を確認できましたので、アカウントの設定は完了です。",
    ro: "Am putut verifica informațiile pe care le-ați furnizat, iar configurarea contului dvs. este acum completă.",
    fr: "Nous avons pu vérifier les informations que vous avez fournies et la configuration de votre compte est désormais terminée.",
    pl: "Udało nam się zweryfikować podane przez Ciebie informacje i konfiguracja Twojego konta została zakończona.",
    es: "Pudimos verificar la información que proporcionó y la configuración de su cuenta ya está completa.",
    it: "Siamo riusciti a verificare le informazioni che hai fornito e la configurazione del tuo account è ora completa.",
    hu: "Sikerült ellenőriznünk az Ön által megadott információkat, és fiókja ezzel befejeződött.",
    el: "Μπορέσαμε να επαληθεύσουμε τις πληροφορίες που παρείχατε και η ρύθμιση του λογαριασμού σας έχει πλέον ολοκληρωθεί.",
    nl: "We hebben de door u verstrekte informatie kunnen verifiëren en het instellen van uw account is nu voltooid.",
    cs: "Podařilo se nám ověřit vámi poskytnuté informace a nastavení vašeho účtu je nyní dokončeno.",
  },
  thanks: {
    en: "Thanks for taking the time to verify your information and helping to keep your account secure.",
    de: "Vielen Dank, dass Sie sich die Zeit genommen haben, Ihre Informationen zu überprüfen und dazu beitragen, die Sicherheit Ihres Kontos zu gewährleisten.",
    pt: "Obrigado por reservar um tempo para verificar suas informações e ajudar a manter sua conta segura.",
    ja: "情報の確認にご協力いただき、アカウントの安全性を確保していただきありがとうございます。",
    ro: "Vă mulțumim pentru timpul acordat pentru a vă verifica informațiile și pentru că vă ajutați să vă păstrați contul în siguranță.",
    fr: "Merci d'avoir pris le temps de vérifier vos informations et de contribuer à la sécurité de votre compte.",
    pl: "Dziękujemy za poświęcenie czasu na weryfikację danych i pomoc w zapewnieniu bezpieczeństwa konta.",
    es: "Gracias por tomarse el tiempo para verificar su información y ayudar a mantener su cuenta segura.",
    it: "Grazie per aver dedicato del tempo alla verifica delle tue informazioni e per aver contribuito a proteggere il tuo account.",
    hu: "Köszönjük, hogy időt szánt adatai ellenőrzésére, és segít fiókja biztonságának megőrzésében.",
    el: "Ευχαριστούμε που αφιερώσατε χρόνο για να επαληθεύσετε τις πληροφορίες σας και για τη βοήθεια που διαθέσατε στην ασφάλεια του λογαριασμού σας.",
    nl: "Bedankt dat u de tijd heeft genomen om uw gegevens te verifiëren en uw account veilig te houden.",
    cs: "Děkujeme, že jste si našli čas na ověření svých údajů a pomohli jste udržet svůj účet v bezpečí.",
  },
  haveNiceDay: {
    en: "Have a nice day.",
    de: "Einen schönen Tag noch.",
    pt: "Tenha um bom dia.",
    ja: "良い１日を。",
    ro: "Va dorim o zi plăcută.",
    fr: "Passe une bonne journée.",
    pl: "Miłego dnia.",
    es: "Que tenga un lindo día.",
    it: "Buona giornata.",
    hu: "Legyen szép napod.",
    el: "Να εχεις μια ωραια μερα.",
    nl: "Prettige dag.",
    cs: "Hezký den.",
  },
};

export default texts;
